# Generated by Django 3.2.9 on 2024-06-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
