# Generated by Django 3.2.9 on 2024-06-10 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
