# Generated by Django 3.2.9 on 2024-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('problems', 'Problems'), ('product_info', 'Product Information'), ('general_info', 'General Information'), ('work_with_us', 'Work with Us'), ('other', 'Other')], max_length=50),
        ),
    ]
